project_name: vine

before:
  hooks:
    - go generate ./...

builds:
  - <<: &base_build
      binary: vine
      main: ./cmd/vine
      env:
        - CGO_ENABLED=0
      ldflags:
        - -s -w
        - -X github.com/harrybrwn/go-vine/cli.version={{ .Version }}
        - -X github.com/harrybrwn/go-vine/cli.commit={{ .Commit }}
    id: linux
    goos: [linux]
    goarch:
      - amd64
      - 386
      - arm64
    #hooks:
    #  post:
    #    - upx {{ .Path }}
  - <<: *base_build
    id: macos
    goos: [darwin]
    goarch: [amd64]
  - <<: *base_build
    id: win
    goos: [windows]
    goarch: [386, amd64]

archives:
  - replacements: &reps
      darwin: MacOS
      linux: Linux
      windows: Windows
      "386": i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - build/completion/*
      - systemd/*
      - README.md

nfpms:
  - <<: &descr
      description: A blockchain
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements: *reps
    maintainer: Harry Brown <harrybrown98@gmail.com>
    license:

    dependencies: []
    suggests: []

    formats:
      - deb
      - rpm

    bindir: /usr/local/bin
    empty_folders: []
    contents:
      # Documentation
      - src: README.md
        dst: /usr/local/etc/vine/README.md

      # Shell Completions
      - src: build/completion/bash
        dst: /usr/share/bash-completion/completions/vine
      - src: build/completion/zsh
        dst: /usr/share/zsh/vendor-completions/_vine

      # systemd
      - src: systemd/vine-ledger.service
        dst: /usr/lib/systemd/system/vine-ledger.service
        file_info:
          mode: 0666 # anyone can read/write

    #scripts:
    #  postinstall: scripts/installation/postinstall.sh
    #  preremove: scripts/installation/preremove.sh

publishers:
  - name: publisher
    cmd: 'scp {{.ArtifactPath}} SERVER:~/.local/share/vine/{{.ArtifactName}}'

brews:
  - <<: *descr
    name: go-vine
    skip_upload: true
    tap:
      owner: harrybrwn
      name: homebrew-tap
    homepage:
    commit_author:
      name: vine-releasebot
      email: harrybrown98@gmail.com
    folder: Formula
    test: |
      system "#{bin}/vine version"
    install: |
      bin.install "vine"

snapcrafts:
  - <<: *descr
    name: vine
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: A blockchain
    grade: stable
    confinement: strict
    publish: false

release:
  disable: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

